# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteDash', '0002_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='likes_count',
        ),
        migrations.AddField(
            model_name='quote',
            name='likes_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='QuoteDash.User'),
            preserve_default=False,
        ),
    ]
