# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteDash', '0003_auto_20180524_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='likes_by',
        ),
    ]
