# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoteDash', '0004_remove_quote_likes_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='likes_by',
            field=models.ManyToManyField(related_name='like', to='QuoteDash.User'),
        ),
    ]
